name: Windows

on:
  push:
    branches-ignore: dev
  pull_request:
    branches-ignore: dev

jobs:
  build:
    runs-on: [windows-latest]
    steps:
      - uses: actions/checkout@v1
      - name: Build
        run: .\ci_scripts\ci_windows_build.cmd
      - name: Test
        run: .\ci_scripts\ci_windows_test.cmd

